# Generated by Django 4.0.6 on 2022-07-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='devtool name')),
                ('kind', models.CharField(max_length=30, verbose_name='종류')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y%M%D', verbose_name='image')),
                ('content', models.TextField(verbose_name='content')),
                ('interest', models.IntegerField(default=0, verbose_name='관심도')),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_devtool', to='posts.devtool')),
            ],
        ),
    ]
