# Generated by Django 4.0.6 on 2022-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('openyear', models.IntegerField(verbose_name='Open Year')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('starpoint', models.IntegerField(verbose_name='Star Point')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('actor', models.CharField(max_length=100, verbose_name='Actor')),
                ('runningtime', models.IntegerField(verbose_name='Running Time')),
                ('review', models.TextField(verbose_name='Review')),
            ],
        ),
    ]
